config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations'}
  resources :users

  root 'problems#index'
  get 'problems/filter' => 'problems#filter', as: 'problems_filter'
  get 'problems/qualification/:id' => 'problems#qualification', as: 'problem_qualification'
  resources :problems, except: :destroy
  get 'knowledge_bases/kb' => 'knowledge_bases#kb', as: 'kbase'
  get 'knowledge_bases/instr' => 'knowledge_bases#instr', as: 'inst'
  resources :knowledge_bases, except: :index

  resources :priorities, except: :show
  resources :departaments
  resources :assets
  resources :organizations
  resources :categories
  resources :uploads
  get 'search/:name' => 'search#index'

end

app/views/notifier/change_state_problem.html.slim
p Hi #{@resource.create_user.email}
p The status of your problem #{@resource.show_id} has changed
p State #{@resource.state}
p= link_to @resource.show_id, edit_problem_url(@resource)
p Answered: #{@resource.last_update_user.firstname} #{@resource.last_update_user.email}

app/views/notifier/send_qualification_request.html.slim
p Hi #{@resource.create_user.email}
p The status of your problem #{@resource.show_id} has changed
p State #{@resource.state}
p Please rate the quality of work!
p= link_to @resource.show_id, problem_qualification_url(@resource)

app/views/notifier/send_thanks.html.slim
p Hi #{@resource.create_user.email}
p Your problem #{@resource.show_id} has closed!
p Thank you for taking the time to evaluate the work of our experts

app/views/notifier/welcome.html.slim
p Hi
  | #{@account.name},
p Thanks for joining service! Good Luck