config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations'}
  resources :users

  root 'problems#index'
  get 'problems/filter' => 'problems#filter', as: 'problems_filter'
  get 'problems/qualification/:id' => 'problems#qualification', as: 'problem_qualification'
  resources :problems, except: :destroy
  get 'knowledge_bases/kb' => 'knowledge_bases#kb', as: 'kbase'
  get 'knowledge_bases/instr' => 'knowledge_bases#instr', as: 'inst'
  resources :knowledge_bases, except: :index

  resources :priorities, except: :show
  resources :departaments
  resources :assets
  resources :organizations
  resources :categories
  resources :uploads
  get 'search/:name' => 'search#index'

end

app/models/organization.rb
class Organization < ActiveRecord::Base
  has_many :departaments

  validates :orgname, presence: true, length: { minimum: 2, maximum: 100 }
  validates :country, :address, presence: true, length: { maximum: 250 }
  validates :phone, presence: true,length: { maximum: 18, minimum: 11 }, format: { with: /\((\+\d{1,2}\s)?(\d{3})\)?(\d{3})[.-](\d{4})/,
                                                       message: I18n.t(:phone_validates) },
            on: [:create, :update], allow_nil: true

  def to_s
    "#{orgname}"
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :set_organization, only: [:show, :edit, :update, :destroy]

  def index
    @organizations = Organization.all
  end

  # GET /organizations/1
  def show
  end

  # GET /organizations/new
  def new
    @organization = Organization.new
  end

  # GET /organizations/1/edit
  def edit
  end

  # POST /organizations
  def create
    @organization = Organization.new(organization_params)
    if @organization.save
      redirect_to organizations_path
    else
      render :new
    end
  end

  # PATCH/PUT /organizations/1
  def update
    if @organization.update(organization_params)
      redirect_to organizations_path
    else
      render :edit
    end
  end

  # DELETE /organizations/1
  def destroy
    @organization.destroy
    redirect_to organizations_path
  end

  private
    def set_organization
      @organization = Organization.find(params[:id])
    end

    def organization_params
      params.require(:organization).permit(:orgname, :address, :phone, :city, :zipcode, :country)
    end
end

app/views/organizations/_form.html.slim
.newform
  = simple_form_for @organization do |f|
    p Organization
    = f.input :orgname
    = f.input :address
    = f.input :phone, :placeholder => "+xx(xxx)xxx-xxxx"
    = f.input :city
    = f.input :zipcode
    = f.country_select :country
    = f.submit :class => 'button tiny radius right'

app/views/organizations/edit.html.slim
=render 'form'

app/views/organizations/index.html.slim
.panel
  table width='100%'
    thead
      th width='20%' Name
      th width='25%' Address
      th width='10%' Phone
      th width='15%' City
      th width='5%' ZIP
      th width='10%' Country
      th width='15%' Actions
    tbody
      - @organizations.each do |p|
        tr
          td= link_to truncate(p.orgname, length: 40), organization_path(p)
          td= truncate(p.address, length: 40)
          td= p.phone
          td= truncate(p.city, length: 40)
          td= p.zipcode
          td= p.country
          td
            - if can? :create, current_user
              = link_to 'Edit', edit_organization_path(p)
              |  |
              = link_to 'Delete', organization_path(p), method: :delete, data: {confirm: 'sure?'}
            - else
              = link_to 'Show', organization_path(p)
  - if can? :create, current_user
    =link_to 'New organization', new_organization_path, class: 'button tiny radius'

app/views/organizations/new.html.slim
=render 'form'

app/views/organizations/show.html.slim
.panel
  table width='100%'
    tbody
      -@organization.attributes.each do |attr|

      tr
        td= Organization.human_attribute_name(:orgname)
        td= @organization.orgname
      tr
        td= Organization.human_attribute_name(:address)
        td= @organization.address
      tr
        td= Organization.human_attribute_name(:phone)
        td= @organization.phone
      tr
        td= Organization.human_attribute_name(:city)
        td= @organization.city
      tr
        td= Organization.human_attribute_name(:zipcode)
        td= @organization.zipcode
      tr
        td= Organization.human_attribute_name(:country)
        td= @organization.country
  = link_to "All organizations", organizations_path, class: 'button tiny radius'