config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations'}
  resources :users

  root 'problems#index'
  get 'problems/filter' => 'problems#filter', as: 'problems_filter'
  get 'problems/qualification/:id' => 'problems#qualification', as: 'problem_qualification'
  resources :problems, except: :destroy
  get 'knowledge_bases/kb' => 'knowledge_bases#kb', as: 'kbase'
  get 'knowledge_bases/instr' => 'knowledge_bases#instr', as: 'inst'
  resources :knowledge_bases, except: :index

  resources :priorities, except: :show
  resources :departaments
  resources :assets
  resources :organizations
  resources :categories
  resources :uploads
  get 'search/:name' => 'search#index'

end

app/models/category.rb
class Category < ActiveRecord::Base

  has_many :problems, foreign_key: 'category_id', class_name: 'Problem'

  validates :description, presence: true, length: { maximum: 250 }
  validates :catname, presence: true, length: { minimum: 2, maximum: 100 }

  self.per_page = 10

  scope :search, -> (query) {where("catname like ? OR description like ?", "%#{query}%", "%#{query}%")}

  def to_s
    "#{catname}"
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  load_and_authorize_resource param_method: :category_params

  before_action :find_by_id, only: [:destroy, :show, :update, :edit]

  def index
    if params[:search]
      @categories = Category.search(params[:search]).paginate(:page => params[:page])
    else
      @categories = Category.all.paginate(:page => params[:page])
    end
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @category.update(category_params)
      redirect_to categories_path
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_path
  end

  def new
    @category = Category.new
  end

  private

    def find_by_id
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:catname, :description, :search)
    end
end

app/views/categories/_form.html.slim
.newform
  = simple_form_for @category do |f|
    = f.input :catname
    = f.input :description
    = f.submit "Save", :class => 'button tiny radius right'

app/views/categories/edit.html.slim
= render 'form'

app/views/categories/index.html.slim
.panel
  table width='100%'
    thead
      th width='25%'= Category.human_attribute_name(:name)
      th width='65%'= Category.human_attribute_name(:description)
      th width='10%' Actions
    tbody
      - @categories.each do |c|
        tr
          td= link_to truncate(c.catname, length: 40), category_path(c)
          td= truncate(c.description, length: 40)
          td
            - if can? :create, current_user
              = link_to 'Edit ', edit_category_path(c)
              |  |
              = link_to ' Delete', category_path(c), method: :delete, data: { confirm: "Are you sure?"}

            - else
              = link_to 'Show', category_path(c)

  = foundation_paginate @categories

- if can? :create, current_user
  = link_to 'New category', new_category_path, class: 'button tiny radius'

app/views/categories/new.html.slim
= render 'form'

app/views/categories/show.html.slim
.panel
  table width='100%'
    tbody
      tr
        td= @category.catname
        td= @category.description

= link_to "List categories", categories_path, class: 'button tiny radius'