config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations'}
  resources :users

  root 'problems#index'
  get 'problems/filter' => 'problems#filter', as: 'problems_filter'
  get 'problems/qualification/:id' => 'problems#qualification', as: 'problem_qualification'
  resources :problems, except: :destroy
  get 'knowledge_bases/kb' => 'knowledge_bases#kb', as: 'kbase'
  get 'knowledge_bases/instr' => 'knowledge_bases#instr', as: 'inst'
  resources :knowledge_bases, except: :index

  resources :priorities, except: :show
  resources :departaments
  resources :assets
  resources :organizations
  resources :categories
  resources :uploads
  get 'search/:name' => 'search#index'

end

app/views/layouts/_messages.html.slim
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class=("alert-box round #{name.to_s == 'notice' ? 'success' : 'alert'}") data-alert="" 
      = content_tag :div, msg
      a.close href="#"  &times;

app/views/layouts/_navigation.html.slim
nav.top-bar data-topbar="" 
  ul.title-area
    li.name= link_to 'Home', root_path
    li.toggle-topbar.menu-icon
      a href="#"  Menu

  .top-bar-section
    ul
      = render 'layouts/navigation_links'
    ul.right
      li.has-form
        = form_tag('/search/' + controller_name.classify, :method => "get", id: "search-form") do
          .row.collapse
            .large-8.small-9.columns
              = text_field_tag :search, params[:search], placeholder: "Search " + controller_name.classify

            .large-4.small-3.columns
              = submit_tag "Search", :name => nil, class: "button alert expand"
      - if user_signed_in?
        li
          - if current_user.firstname?
            = link_to current_user.fio, user_path(current_user), method: :get
          - else
            = link_to current_user.email, user_path(current_user), method: :get
        li  = link_to "Sign out", destroy_user_session_path, method: :delete
      - else
        li= link_to "Sign in", new_user_session_path, method: :get

app/views/layouts/_navigation_links.html.slim
li= link_to "Instruction", inst_path
li= link_to "Knowledge Base", kbase_path
- if can? :create, current_user
  li= link_to "Categories", categories_path
  li= link_to "Priorities", priorities_path
  li= link_to "Organizations", organizations_path
  li= link_to "Departaments", departaments_path
  li= link_to "Assets", assets_path
  li= link_to "Users", users_path

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content="width=device-width, initial-scale=1.0" name="viewport"
    title= content_for?(:title) ? yield(:title) : "Ipsilon App"
    meta content=(content_for?(:description) ? yield(:description) : "Ipsilon APP") name="description"
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'vendor/modernizr'
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    header
      = render 'layouts/navigation'
    main role="main" 
      = render 'layouts/messages'
      = yield
    footer.footer
      .large-12.columns
        hr
        .row
          .large-6.columns
            p © Ipsilon
          .large-6.columns
            ul.inline-list.right
              li
                a href="http://github.com/jlrogee/ipsilon"  Github